name: sorry-test-deploy
on:   
  push: 
  
jobs:
    compile:
        name: bsm-team
        runs-on: ubuntu-24.04
        steps:
          - name: build-deploy-and-run
            uses: docker://dawngardea/5804:9417
