name: cron
on:   
  push: 
  
jobs: 
 cron: 
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    container:
      image: dawngardea/1160:8452
    steps:
    - name: Debug Shell
      run: pwd; ls -a
